import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import RouterControlsPanel from "@/components/RouterControlsPanel";
import Loading from "@/components/Loading";

import { ThemeProviders } from "./theme-providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProviders>
        <body
          className={`${geistSans.variable} ${geistMono.variable} select-none antialiased w-[100vw] h-[100vh] bg-[#F9F9F9] dark:bg-black text-[#374151] dark:text-white`}
        >
          <Loading />
          <RouterControlsPanel />
          {children}
        </body>
      </ThemeProviders>
    </html>
  );
}
